import 'package:flutter/material.dart';

const PRIMARY_COLOR = Color(0xFF26A69A);
const ACTION_BUTTON_BACK_COLOR = Color(0xFF26C6DA);
const BACKGROUND_COLOR = Color(0xff764abc);
const LOGIN_BUTTON_BACK_COLOR = Color(0xFF5C6BC0);
const LOGOUT_BUTTON_BACK_COLOR = Color(0xFFE0E0E0);
const LOGOUT_BUTTON_TEXT_COLOR = Color(0xFFFF7043);
const SEARCH_BUTTON_BACK_COLOR = Color(0xFF3F51B5);
const OUTLINE_BUTTON_TEXT_COLOR = Color(0xFFFFFFFF);
const OUTLINE_BUTTON_BACK_COLOR = Color(0xFF26A69A);
const SCANNED_BOX_BACK_COLOR = Color(0XFF283593);